CREATE TABLE RATE (
Rate_Id INT NOT NULL AUTO_INCREMENT,
Rate_Type BOOL NOT NULL,
Rate_Item INT NOT NULL,
Rate_User INT NOT NULL,
Rate_Size INT NOT NULL,
PRIMARY KEY (Rate_Id),
FOREIGN KEY (Rate_Item) REFERENCES MOVIE(Mov_Id),
FOREIGN KEY (Rate_Item) REFERENCES TV(TV_Id),
FOREIGN KEY (Rate_User) REFERENCES USER_TABLE(User_Id));
