CREATE TABLE CAST_TABLE (
Ch_Id INT NOT NULL AUTO_INCREMENT,
Ch_Name VARCHAR(30) NOT NULL,
Ch_Country VARCHAR(30) NOT NULL,
Ch_DOB DATE NOT NULL,
Ch_Des TEXT NOT NULL,
Ch_Link TEXT NOT NULL,
PRIMARY KEY (Ch_Id));
