CREATE TABLE DIRECTOR (
Dir_Id INT NOT NULL AUTO_INCREMENT,
Dir_Name VARCHAR(30) NOT NULL,
Dir_Country VARCHAR(30) NOT NULL,
Dir_DOB DATE NOT NULL,
Dir_Des TEXT NOT NULL,
Dir_Link TEXT NOT NULL,
PRIMARY KEY (Dir_Id));
