CREATE TABLE `ratingdb`.`movie` (
  `Mov_Id` INT NOT NULL AUTO_INCREMENT,
  `Mov_Name` VARCHAR(55) NOT NULL,
  `Mov_Year` INT NOT NULL,
  `Mov_Time` INT NOT NULL,
  `Mov_Lang` VARCHAR(55) NOT NULL,
  `Mov_Country` VARCHAR(55) NOT NULL,
  `Mov_Age` VARCHAR(10) NULL,
  `Mov_Desc` TEXT NOT NULL,
  `Mov_Type` VARCHAR(55) NULL,
  `Mov_Link` TEXT NOT NULL,
  `Mov_Cast_1` INT NOT NULL,
  `Mov_Cast_2` INT NULL,
  `Mov_Cast_3` INT NULL,
  `Mov_Dir` INT NOT NULL,
  `Mov_Rate` INT NOT NULL,
  PRIMARY KEY (`Mov_Id`));