CREATE TABLE USER_TABLE (
User_Id INT NOT NULL AUTO_INCREMENT,
User_FName VARCHAR(15) NOT NULL,
User_LName VARCHAR(15) NOT NULL,
User_DOB DATE NOT NULL,
User_EMail VARCHAR(30) NOT NULL,
User_Pswd VARCHAR(30) NOT NULL,
User_Country VARCHAR(30) NOT NULL,
User_Link TEXT NOT NULL,
User_Type BOOL NOT NULL,
PRIMARY KEY (User_Id));